 --[[                                                                           ]]--
 --[[  Automatically generated code (do not edit)                               ]]--
 --[[                                                                           ]]--
 --[[                                                                           ]]--
 --[[  Scenario                                                                 ]]--
 --[[                                                                           ]]--
Scenario = {
  next_area_id = '1',
  --[[                                                                           ]]--
  --[[  Props                                                                    ]]--
  --[[                                                                           ]]--
  Props = {},
  --[[                                                                           ]]--
  --[[  Areas                                                                    ]]--
  --[[                                                                           ]]--
  Areas = {},
  --[[                                                                           ]]--
  --[[  Markers                                                                  ]]--
  --[[                                                                           ]]--
  MasterChain = {
    ['_MASTERCHAIN_'] = {
      Markers = {
        ['Expansion Area 09'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 318.50, 17.92969, 949.50 ),
        },
        ['Naval Area 05'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 787.50, 17.50, 364.50 ),
        },
        ['Expansion Area 01'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 974.50, 17.92969, 568.50 ),
        },
        ['Combat Zone 07'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 931.50, 17.50, 234.50 ),
        },
        ['Rally Point 03'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['type'] = STRING( 'Rally Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 526.50, 17.92969, 873.50 ),
        },
        ['Naval Area 00'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 240.50, 17.50, 355.50 ),
        },
        ['Island 19'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 723.50, 19.4375, 509.50 ),
        },
        ['Mass 23'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 841.50, 17.91406, 703.50 ),
        },
        ['Mass 9'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 525.50, 17.94531, 910.50 ),
        },
        ['Mass 39'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 844.50, 17.95313, 337.50 ),
        },
        ['Mass 17'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 521.50, 17.92969, 114.50 ),
        },
        ['Mass 50'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 177.50, 17.92969, 720.50 ),
        },
        ['Defensive Point 11'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 479.50, 17.96094, 922.50 ),
        },
        ['Mass 14'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 471.50, 18.15625, 916.50 ),
        },
        ['Expansion Area 03'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 698.50, 17.92969, 78.50 ),
        },
        ['Mass 41'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 850.50, 17.9375, 303.50 ),
        },
        ['Naval Area 01'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 120.50, 17.50, 275.50 ),
        },
        ['Expansion Area 14'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 404.50, 19.44531, 333.50 ),
        },
        ['Rally Point 01'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['type'] = STRING( 'Rally Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 819.50, 17.92969, 317.50 ),
        },
        ['Combat Zone 10'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 247.50, 17.50, 111.50 ),
        },
        ['Protected Experimental Construction 00'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 843.50, 17.84375, 274.50 ),
        },
        ['Combat Zone 12'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 46.50, 17.50, 503.50 ),
        },
        ['Island 20'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( -0.10472, 0, 0 ),
          ['position'] = VECTOR3( 650.50, 17.92188, 357.50 ),
        },
        ['Combat Zone 00'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 682.50, 17.50, 619.50 ),
        },
        ['Rally Point 02'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['type'] = STRING( 'Rally Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 847.50, 17.92969, 684.50 ),
        },
        ['Combat Zone 03'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 329.50, 17.50, 407.50 ),
        },
        ['Expansion Area 06'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 45.50, 17.92969, 437.50 ),
        },
        ['Mass 37'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 139.50, 18.03125, 332.50 ),
        },
        ['Defensive Point 03'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 819.50, 17.84375, 341.50 ),
        },
        ['Mass 71'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 54.50, 17.92969, 578.50 ),
        },
        ['Expansion Area 04'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 308.50, 17.91406, 78.50 ),
        },
        ['Defensive Point 10'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 533.50, 17.91406, 920.50 ),
        },
        ['Expansion Area 08'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 197.50, 17.92969, 875.50 ),
        },
        ['Mass 30'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 851.50, 18.46094, 749.50 ),
        },
        ['Mass 72'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 46.50, 17.92969, 439.50 ),
        },
        ['Mass 12'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( -0.0174533, 0, 0 ),
          ['position'] = VECTOR3( 547.50, 17.9375, 878.50 ),
        },
        ['Mass 67'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 824.50, 17.92188, 869.50 ),
        },
        ['Island 06'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 705.50, 17.92969, 944.50 ),
        },
        ['Naval Area 04'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 892.50, 17.50, 272.50 ),
        },
        ['Combat Zone 09'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 503.50, 17.50, 45.50 ),
        },
        ['Naval Area 11'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 124.50, 17.50, 753.50 ),
        },
        ['Defensive Point 17'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 147.50, 17.89844, 317.50 ),
        },
        ['Mass 22'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 471.50, 17.94531, 104.50 ),
        },
        ['Naval Area 02'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 513.50, 17.50, 194.50 ),
        },
        ['Defensive Point 05'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 849.50, 17.92969, 285.50 ),
        },
        ['Expansion Area 13'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 617.50, 19.40625, 335.50 ),
        },
        ['Island 11'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 693.50, 17.92969, 75.50 ),
        },
        ['Expansion Area 00'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 969.50, 17.92969, 429.50 ),
        },
        ['Mass 68'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 705.50, 17.92969, 946.50 ),
        },
        ['Mass 48'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 197.50, 17.92969, 700.50 ),
        },
        ['Island 12'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 308.50, 17.91406, 79.50 ),
        },
        ['Combat Zone 02'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0.00, -0, 0 ),
          ['position'] = VECTOR3( 512.50, 17.50, 310.50 ),
        },
        ['Island 07'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 825.50, 17.91406, 872.50 ),
        },
        ['Mass 10'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 505.50, 17.92969, 910.50 ),
        },
        ['Naval Area 08'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 513.50, 17.50, 955.50 ),
        },
        ['Defensive Point 07'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 887.50, 17.94531, 706.50 ),
        },
        ['Naval Area 09'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 500.50, 17.50, 810.50 ),
        },
        ['Mass 29'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 822.50, 18.08594, 716.50 ),
        },
        ['Mass 64'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 818.50, 17.92969, 146.50 ),
        },
        ['Defensive Point 06'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 828.50, 17.88281, 681.50 ),
        },
        ['Expansion Area 10'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 703.50, 17.92969, 946.50 ),
        },
        ['Protected Experimental Construction 03'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 142.50, 17.94531, 703.50 ),
        },
        ['Combat Zone 04'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 324.50, 17.50, 610.50 ),
        },
        ['Combat Zone 14'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 260.50, 17.50, 909.50 ),
        },
        ['Expansion Area 15'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 300.50, 19.45313, 503.50 ),
        },
        ['Expansion Area 07'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 50.50, 17.92969, 577.50 ),
        },
        ['Island 03'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 182.50, 17.92969, 317.50 ),
        },
        ['Naval Area 10'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 233.50, 17.50, 647.50 ),
        },
        ['Island 16'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 197.50, 17.92969, 875.50 ),
        },
        ['Island 08'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 974.50, 17.92969, 568.50 ),
        },
        ['Rally Point 04'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['type'] = STRING( 'Rally Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 202.50, 17.92969, 703.50 ),
        },
        ['Combat Zone 01'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( -0.00872665, 0, 0 ),
          ['position'] = VECTOR3( 622.50, 19.42188, 343.50 ),
        },
        ['Mass 33'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 178.50, 17.92969, 302.50 ),
        },
        ['Mass 62'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 310.50, 17.91406, 77.50 ),
        },
        ['Island 17'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 321.50, 17.92969, 949.50 ),
        },
        ['Defensive Point 01'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 532.50, 17.96094, 103.50 ),
        },
        ['Mass 35'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 185.50, 18.10938, 274.50 ),
        },
        ['ARMY_6'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 178.50, 17.92969, 704.50 ),
        },
        ['ARMY_3'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 858.50, 17.92969, 707.50 ),
        },
        ['Mass 46'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 852.50, 17.92969, 354.50 ),
        },
        ['Island 18'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 613.50, 19.39063, 693.50 ),
        },
        ['Mass 13'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 473.50, 17.75, 878.50 ),
        },
        ['Mass 8'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 525.50, 17.92969, 884.50 ),
        },
        ['Island 05'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 513.50, 17.92969, 891.50 ),
        },
        ['Mass 69'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 320.50, 17.92969, 949.50 ),
        },
        ['Mass 55'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 407.50, 19.44531, 332.50 ),
        },
        ['Expansion Area 16'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 396.50, 19.375, 683.50 ),
        },
        ['Mass 7'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 505.50, 17.90625, 884.50 ),
        },
        ['Mass 59'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 401.50, 19.34375, 683.50 ),
        },
        ['Defensive Point 09'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 514.50, 17.88281, 859.50 ),
        },
        ['Island 01'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 842.50, 17.92969, 318.50 ),
        },
        ['Island 21'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 404.50, 19.38281, 328.50 ),
        },
        ['Defensive Point 13'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 172.50, 17.97656, 734.50 ),
        },
        ['Mass 47'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 183.50, 17.88281, 686.50 ),
        },
        ['Rally Point 05'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['type'] = STRING( 'Rally Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 184.50, 17.92969, 343.50 ),
        },
        ['ARMY_1'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 516.50, 17.92969, 895.50 ),
        },
        ['Protected Experimental Construction 05'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 139.50, 17.79688, 323.50 ),
        },
        ['Combat Zone 11'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 83.50, 17.50, 252.50 ),
        },
        ['Mass 65'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 969.50, 17.92969, 429.50 ),
        },
        ['Defensive Point 08'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 856.50, 18.10938, 743.50 ),
        },
        ['Island 02'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 506.50, 17.92969, 125.50 ),
        },
        ['Mass 51'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 134.50, 18.0625, 687.50 ),
        },
        ['Mass 60'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 301.50, 19.44531, 502.50 ),
        },
        ['Mass 24'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 855.50, 17.92969, 689.50 ),
        },
        ['Defensive Point 16'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 169.50, 17.875, 285.50 ),
        },
        ['Expansion Area 11'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 823.50, 17.91406, 874.50 ),
        },
        ['Mass 25'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 875.50, 17.96094, 709.50 ),
        },
        ['Combat Zone 13'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 96.50, 17.50, 759.50 ),
        },
        ['Mass 58'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 616.50, 19.39844, 693.50 ),
        },
        ['Rally Point 00'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'FF808000' ),
          ['type'] = STRING( 'Rally Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 492.50, 17.92969, 149.50 ),
        },
        ['Mass 16'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 521.50, 17.89844, 140.50 ),
        },
        ['Mass 36'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 214.50, 17.92969, 302.50 ),
        },
        ['Protected Experimental Construction 04'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 478.50, 17.875, 102.50 ),
        },
        ['Island 15'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 51.50, 17.92969, 577.50 ),
        },
        ['Naval Area 07'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 789.50, 17.50, 651.50 ),
        },
        ['Island 04'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 176.50, 17.92969, 703.50 ),
        },
        ['Mass 54'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 180.50, 17.92969, 744.50 ),
        },
        ['Mass 40'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 830.50, 17.92969, 323.50 ),
        },
        ['Defensive Point 15'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 205.50, 17.86719, 339.50 ),
        },
        ['Island 10'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 816.50, 17.92969, 148.50 ),
        },
        ['Mass 38'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 173.50, 17.875, 362.50 ),
        },
        ['Defensive Point 04'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 876.50, 17.89063, 313.50 ),
        },
        ['Combat Zone 05'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 510.50, 17.50, 706.50 ),
        },
        ['Mass 45'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 886.50, 18.10156, 330.50 ),
        },
        ['Mass 42'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 864.50, 17.91406, 317.50 ),
        },
        ['Mass 20'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 547.50, 17.96875, 104.50 ),
        },
        ['Mass 44'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 836.50, 18.00, 274.50 ),
        },
        ['ARMY_2'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 512.50, 17.92969, 129.50 ),
        },
        ['Combat Zone 17'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 942.50, 17.50, 766.50 ),
        },
        ['Combat Zone 06'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 974.50, 17.50, 496.50 ),
        },
        ['Island 09'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 967.50, 17.92969, 430.50 ),
        },
        ['Mass 49'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 163.50, 17.92969, 706.50 ),
        },
        ['Expansion Area 12'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 720.50, 19.42969, 508.50 ),
        },
        ['Expansion Area 05'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 188.50, 17.90625, 154.50 ),
        },
        ['Island 22'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 298.50, 19.45313, 501.50 ),
        },
        ['Mass 28'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 895.50, 17.92969, 692.50 ),
        },
        ['Island 00'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 854.50, 17.92969, 703.50 ),
        },
        ['Mass 11'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 549.50, 18.03125, 916.50 ),
        },
        ['Protected Experimental Construction 02'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 553.50, 17.9375, 919.50 ),
        },
        ['Island 14'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 49.50, 17.92969, 437.50 ),
        },
        ['Mass 61'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 190.50, 17.89844, 155.50 ),
        },
        ['Mass 57'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 723.50, 19.42969, 513.50 ),
        },
        ['Mass 21'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 469.50, 18.00781, 148.50 ),
        },
        ['Island 23'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 398.50, 19.36719, 679.50 ),
        },
        ['Mass 31'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 198.50, 17.92969, 322.50 ),
        },
        ['Mass 27'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 858.50, 17.92969, 665.50 ),
        },
        ['Combat Zone 08'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 755.50, 17.50, 109.50 ),
        },
        ['Mass 52'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 162.50, 18.30469, 665.50 ),
        },
        ['ARMY_5'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 847.50, 17.91406, 319.50 ),
        },
        ['Naval Area 03'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 510.50, 17.50, 60.50 ),
        },
        ['ARMY_4'] = {
          ['color'] = STRING( 'ff800080' ),
          ['type'] = STRING( 'Blank Marker' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 179.50, 17.92969, 315.50 ),
        },
        ['Expansion Area 02'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['type'] = STRING( 'Expansion Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 815.50, 17.92969, 149.50 ),
        },
        ['Mass 63'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 696.50, 17.92969, 77.50 ),
        },
        ['Mass 56'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 622.50, 19.42188, 338.50 ),
        },
        ['Island 13'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Island' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 187.50, 17.91406, 156.50 ),
        },
        ['Mass 53'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 219.50, 17.92969, 715.50 ),
        },
        ['Defensive Point 02'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 489.50, 17.92188, 103.50 ),
        },
        ['Naval Area 06'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000FF' ),
          ['type'] = STRING( 'Naval Area' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 911.50, 17.50, 747.50 ),
        },
        ['Defensive Point 12'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 204.50, 17.85938, 683.50 ),
        },
        ['Mass 34'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 164.50, 17.92969, 316.50 ),
        },
        ['Mass 43'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 800.50, 17.80469, 300.50 ),
        },
        ['Mass 70'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 197.50, 17.92969, 874.50 ),
        },
        ['Mass 18'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 501.50, 17.9375, 114.50 ),
        },
        ['Defensive Point 14'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 140.50, 17.92969, 700.50 ),
        },
        ['Protected Experimental Construction 01'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff0000AA' ),
          ['type'] = STRING( 'Protected Experimental Construction' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 896.50, 17.85938, 698.50 ),
        },
        ['Mass 32'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 184.50, 17.92969, 336.50 ),
        },
        ['Mass 15'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 501.50, 17.92969, 140.50 ),
        },
        ['Mass 26'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 861.50, 17.92969, 723.50 ),
        },
        ['Mass 66'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 975.50, 17.92969, 570.50 ),
        },
        ['Combat Zone 16'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 763.50, 17.50, 911.50 ),
        },
        ['Combat Zone 15'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 516.50, 17.50, 973.50 ),
        },
        ['Mass 19'] = {
          ['size'] = FLOAT( 1.00 ),
          ['resource'] = BOOLEAN( true ),
          ['amount'] = FLOAT( 100.00 ),
          ['color'] = STRING( 'ff808080' ),
          ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
          ['type'] = STRING( 'Mass' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 545.50, 18.28906, 148.50 ),
        },
        ['Defensive Point 00'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008000' ),
          ['type'] = STRING( 'Defensive Point' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 509.50, 17.875, 159.50 ),
        },
        ['Combat Zone 18'] = {
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff800000' ),
          ['type'] = STRING( 'Combat Zone' ),
          ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
          ['orientation'] = VECTOR3( 0, -0, 0 ),
          ['position'] = VECTOR3( 509.50, 17.50, 514.50 ),
        },
        ['Expansion Area 17'] = {
          ['type'] = STRING( 'Expansion Area' ),
          ['position'] = VECTOR3( 626.50, 19.29688, 687.50 ),
          ['orientation'] = VECTOR3( 0.00, 0.00, 0.00 ),
          ['hint'] = BOOLEAN( true ),
          ['color'] = STRING( 'ff008080' ),
          ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
        },
      },
    },
  },
  Chains = {},
  --[[                                                                           ]]--
  --[[  Orders                                                                   ]]--
  --[[                                                                           ]]--
  next_queue_id = '1',
  Orders = {},
  --[[                                                                           ]]--
  --[[  Platoons                                                                 ]]--
  --[[                                                                           ]]--
  next_platoon_id = '1',
  Platoons = {},
  --[[                                                                           ]]--
  --[[  Armies                                                                   ]]--
  --[[                                                                           ]]--
  next_army_id = '7',
  next_group_id = '1',
  next_unit_id = '7',
  Armies = {
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_3'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_1'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_2'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_4'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_5'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    --[[                                                                           ]]--
    --[[  Army                                                                     ]]--
    --[[                                                                           ]]--
    ['ARMY_6'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    ['ARMY_9'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
    ['NEUTRAL_CIVILIAN'] = {
      personality = '',
      plans = '',
      color = 0,
      faction = 0,
      Economy = {mass = 0, energy = 0},
      Alliances = {},
      ['Units'] = GROUP {
        orders = '',
        platoon = '',
        Units = {
          ['INITIAL'] = GROUP {
            orders = '',
            platoon = '',
            Units = {},
          },
        },
      },
      PlatoonBuilders = {
        next_platoon_builder_id = '0',
        Builders = {},
      },
    },
  },
}
