--[[  Scenario                                                           		]]--
--[[  																					]]--
--[[	Generated by FAF Map Editor								]]--
--[[	Contact: ozonexo3@gmail.com								]]--
--[[																					]]--
Scenario = {
    next_area_id = '4',
    --[[																				]]--
    --[[  Props                                                                    ]]--
    --[[																				]]--
    Props = {
    },
    --[[																				]]--
    --[[  Areas                                                                    ]]--
    --[[																				]]--
    Areas = {
        ['AREA_1'] = {
[AREA]
        },
    },
    --[[																				]]--
    --[[  Markers																]]--
    --[[																				]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
[MARKERS]
            },
        },
    },
    Chains = {
[CHAINS]
    },
    --[[																				]]--
    --[[  Orders																	]]--
    --[[																				]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[																				]]--
    --[[  Platoons																]]--
    --[[																				]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[																				]]--
    --[[  Armies																	]]--
    --[[																				]]--
    next_army_id = '5',
    next_group_id = '1',
    next_unit_id = '2',
    Armies = 
    {
[ARMYS]
    },
}