--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '4',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 12, 60.5, 500, 452 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Mass1_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_1' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 38.5, 27.9492, 330.5 ),
                },
                ['Naval Area 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 176.178, 15.1013, 84.8458 ),
                },
                ['Mass14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 80.5, 27.9707, 332.5 ),
                },
                ['Combat Zone 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 181.636, 12.5504, 335.045 ),
                },
                ['Defensive Point 23'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 312.983, 12.7686, 132.825 ),
                },
                ['Rally Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 291.5, 24.6, 372.5 ),
                },
                ['Mass_Mid_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 268.5, 26.9922, 226.5 ),
                },
                ['Hydrocarbon 50'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 432.5, 27.9922, 346.5 ),
                },
                ['Mass71'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 442.5, 27.9922, 92.5 ),
                },
                ['Mass35'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 9.5, 27.9844, 230.5 ),
                },
                ['Mass_Mid_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 244.5, 26.9922, 284.5 ),
                },
                ['Hydrocarbon2 78'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 432.5, 27.9922, 166.5 ),
                },
                ['Mass1_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_1' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 24.5, 27.9922, 340.5 ),
                },
                ['Naval Area 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 450.53, 19.9375, 233.203 ),
                },
                ['Defensive Point 11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 260.757, 31.9879, 331.494 ),
                },
                ['Naval Area 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 345.631, 15.0715, 408.764 ),
                },
                ['Expansion Area 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 22.3127, 27.9922, 382.876 ),
                },
                ['Mass11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.5, 27.9922, 420.5 ),
                },
                ['Naval Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 61.7549, 24.6, 233.819 ),
                },
                ['Rally Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 189.5, 24.6, 194.5 ),
                },
                ['Combat Zone 10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 192.041, 8.94531, 157.168 ),
                },
                ['Protected Experimental Construction 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 479.117, 27.9922, 373.352 ),
                },
                ['Combat Zone 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 251.783, 11.7213, 375.779 ),
                },
                ['Rally Point 08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 224.842, 9.56659, 135.824 ),
                },
                ['Mass8_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_8' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 452.5, 27.9922, 112.5 ),
                },
                ['Rally Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 332.245, 12.3475, 151.817 ),
                },
                ['Combat Zone 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 418.069, 27.1103, 443.365 ),
                },
                ['ARMY_8'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 452.5, 27.9922, 122.5 ),
                },
                ['Mass_34'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_34' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 27.9922, 137.5 ),
                },
                ['Defensive Point 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 69.2047, 27.9922, 421.017 ),
                },
                ['Mass7_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_7' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 464.5, 27.9922, 172.5 ),
                },
                ['Mass54'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 432.5, 27.9707, 332.5 ),
                },
                ['Expansion Area 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 73.1502, 27.9922, 356.256 ),
                },
                ['Defensive Point 10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 266.166, 26.9922, 230.469 ),
                },
                ['Mass31'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.5, 27.9922, 92.5 ),
                },
                ['Defensive Point 24'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 338.817, 9.58002, 252.994 ),
                },
                ['Expansion Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 20.2852, 27.9922, 126.502 ),
                },
                ['Mass70'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 391.5, 26.9863, 74.5 ),
                },
                ['Mass13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 27.9922, 399.5 ),
                },
                ['Naval Area 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 339.285, 15.6806, 88.4304 ),
                },
                ['Combat Zone 09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 331.915, 12.3087, 142.747 ),
                },
                ['Defensive Point 17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.6493, 27.9922, 91.6961 ),
                },
                ['Mass74'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 432.5, 27.9707, 180.5 ),
                },
                ['Naval Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 447.535, 19.9375, 281.811 ),
                },
                ['Defensive Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 441.773, 27.9922, 420.922 ),
                },
                ['Mass8_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_8' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 462.5, 27.9922, 122.5 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 80.5, 27.9922, 346.5 ),
                },
                ['Defensive Point 19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 70.2293, 27.9539, 329.09 ),
                },
                ['Expansion Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 494.669, 27.9922, 386.201 ),
                },
                ['Mass2_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_2' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 50.5, 27.9922, 390.5 ),
                },
                ['Hydrocarbon_78'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_78' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 27.9922, 124.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 431.5, 24.6, 258.5 ),
                },
                ['Mass73'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 27.9922, 113.5 ),
                },
                ['Hydrocarbon_12'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_12' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 27.9922, 387.5 ),
                },
                ['Mass72'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 499.5, 27.9824, 200.5 ),
                },
                ['Hydrocarbon_34'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_34' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 27.9922, 124.5 ),
                },
                ['Defensive Point 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 377.116, 36.0005, 286.255 ),
                },
                ['Rally Point 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 191.414, 12.5262, 386.119 ),
                },
                ['Protected Experimental Construction 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 33.4423, 27.9922, 135.007 ),
                },
                ['Mass15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 9.5, 27.9844, 282.5 ),
                },
                ['Mass4_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_4' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 27.9922, 136.5 ),
                },
                ['Mass4_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_4' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 50.5, 27.9922, 122.5 ),
                },
                ['Mass3_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_3' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 48.5, 27.9922, 172.5 ),
                },
                ['Mass2_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_2' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 27.9922, 400.5 ),
                },
                ['Expansion Area 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 444.661, 27.9922, 356.097 ),
                },
                ['Defensive Point 29'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 86.1193, 28.0606, 371.001 ),
                },
                ['Mass1_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_1' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 38.5, 27.9922, 354.5 ),
                },
                ['Defensive Point 21'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 433.298, 27.9622, 179.841 ),
                },
                ['Rally Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 172.836, 9.05945, 255.358 ),
                },
                ['Defensive Point 25'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 174.908, 9.18097, 255.943 ),
                },
                ['Mass2_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_2' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 74.5, 27.9922, 390.5 ),
                },
                ['Defensive Point 30'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 424.554, 27.9922, 374.724 ),
                },
                ['Mass7_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_7' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 488.5, 27.9922, 172.5 ),
                },
                ['Mass50'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 391.5, 26.9863, 438.5 ),
                },
                ['Rally Point 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 339.49, 9.87163, 249.871 ),
                },
                ['Defensive Point 13'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 107.461, 19.443, 255.53 ),
                },
                ['Defensive Point 28'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 89.5172, 27.9922, 137.023 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 38.5, 27.9922, 340.5 ),
                },
                ['Protected Experimental Construction 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 33.6462, 27.9922, 373.795 ),
                },
                ['Mass3_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_3' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 24.5, 27.9922, 172.5 ),
                },
                ['Mass7_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_7' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 474.5, 27.9922, 158.5 ),
                },
                ['Defensive Point 08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 377.635, 36, 223.714 ),
                },
                ['Mass32'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 13.5, 27.9824, 200.5 ),
                },
                ['Mass34'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 80.5, 27.9707, 180.5 ),
                },
                ['Mass5_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_5' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 474.5, 27.9492, 330.5 ),
                },
                ['Mass33'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 27.9922, 113.5 ),
                },
                ['Defensive Point 16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 120.777, 26.9766, 74.285 ),
                },
                ['Defensive Point 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 202.125, 12.102, 378.488 ),
                },
                ['Mass2_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_2' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 27.9922, 376.5 ),
                },
                ['ARMY_7'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 474.5, 27.9922, 172.5 ),
                },
                ['Mass_12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_12' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 27.9922, 375.5 ),
                },
                ['Rally Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 179.904, 12.7891, 320.618 ),
                },
                ['Island 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 256.566, 37.7523, 74.7763 ),
                },
                ['Hydrocarbon2 34'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 80.5, 27.9922, 166.5 ),
                },
                ['Combat Zone 11'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 255.062, 26.7493, 254.161 ),
                },
                ['Island 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 254.5, 26.9883, 259.5 ),
                },
                ['ARMY_6'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 452.5, 27.9922, 390.5 ),
                },
                ['Mass5_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_5' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 474.5, 27.9922, 354.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 78.5, 24.6, 258.5 ),
                },
                ['Protected Experimental Construction 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 484.78, 27.9922, 130.791 ),
                },
                ['Mass8_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_8' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 452.5, 27.9922, 136.5 ),
                },
                ['Defensive Point 31'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 422.834, 27.9922, 132.837 ),
                },
                ['Defensive Point 12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 249.323, 31.9379, 180.724 ),
                },
                ['Defensive Point 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 396.83, 26.9922, 438.86 ),
                },
                ['Combat Zone 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 89.1791, 27.3697, 67.5764 ),
                },
                ['Mass52'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 499.5, 27.9824, 312.5 ),
                },
                ['Defensive Point 22'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 209.009, 9.35028, 136.649 ),
                },
                ['Mass6_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_6' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 462.5, 27.9922, 390.5 ),
                },
                ['Mass4_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_4' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 74.5, 27.9922, 122.5 ),
                },
                ['Mass75'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 503.5, 27.9844, 230.5 ),
                },
                ['Defensive Point 09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 246.184, 26.9922, 278.532 ),
                },
                ['Defensive Point 27'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 395.822, 26.9855, 72.6758 ),
                },
                ['Mass5_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_5' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 464.5, 27.9922, 340.5 ),
                },
                ['Naval Area 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 59.941, 19.9452, 283.918 ),
                },
                ['Mass4_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_4' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 27.9922, 112.5 ),
                },
                ['Expansion Area 05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 69.6582, 27.9922, 161.394 ),
                },
                ['Mass55'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 503.5, 27.9844, 282.5 ),
                },
                ['Mass12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 13.5, 27.9824, 312.5 ),
                },
                ['Mass3_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_3' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 38.5, 27.9492, 182.5 ),
                },
                ['Mass6_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_6' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 438.5, 27.9922, 390.5 ),
                },
                ['Defensive Point 26'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 442.842, 27.9922, 94.9518 ),
                },
                ['Combat Zone 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 100.492, 26.9922, 447.54 ),
                },
                ['Mass6_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_6' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 452.5, 27.9922, 400.5 ),
                },
                ['Mass1_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_1' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 48.5, 27.9922, 340.5 ),
                },
                ['Mass30'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 121.5, 26.9863, 74.5 ),
                },
                ['Combat Zone 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 423.963, 27.4428, 66.0257 ),
                },
                ['Defensive Point 14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 134.5, 36.0254, 284.5 ),
                },
                ['Defensive Point 15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 132.474, 36.2609, 228.65 ),
                },
                ['Hydrocarbon_56'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_56' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 27.9922, 387.5 ),
                },
                ['Combat Zone 08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 328.814, 8.94531, 320.656 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 27.9922, 390.5 ),
                },
                ['Mass7_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_7' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 474.5, 27.9492, 182.5 ),
                },
                ['ARMY_4'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 60.5, 27.9922, 122.5 ),
                },
                ['ARMY_5'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 474.5, 27.9922, 340.5 ),
                },
                ['Mass8_2'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_8' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 738.5, 27.9922, 122.5 ),
                },
                ['Protected Experimental Construction 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 46.9011, 19.9922, 260.673 ),
                },
                ['Mass_78'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_78' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 27.9922, 137.5 ),
                },
                ['Defensive Point 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 392.1, 18.0883, 256.693 ),
                },
                ['Defensive Point 20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 434.115, 27.9473, 329.246 ),
                },
                ['Naval Area 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 175.498, 14.8861, 414.433 ),
                },
                ['Mass_56'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_56' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 27.9922, 375.5 ),
                },
                ['Mass5_4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_5' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 488.5, 27.9922, 340.5 ),
                },
                ['Expansion Area 06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 448.476, 27.9922, 156.314 ),
                },
                ['Defensive Point 18'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 75.8863, 27.9413, 182.255 ),
                },
                ['Mass53'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 501.5, 27.9922, 399.5 ),
                },
                ['Mass51'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 442.5, 27.9922, 420.5 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 468.61, 19.9718, 256.703 ),
                },
                ['Island 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 254.09, 45.0035, 443.993 ),
                },
                ['Defensive Point 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 111.995, 26.9922, 442.813 ),
                },
                ['Rally Point 07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 332.016, 8.94531, 319.257 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 497.299, 27.9922, 125.725 ),
                },
                ['Mass10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 121.5, 26.9863, 438.5 ),
                },
                ['Mass6_1'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_6' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 452.5, 27.9922, 376.5 ),
                },
                ['Mass3_3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_3' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 38.5, 27.9922, 158.5 ),
                },
                ['Defensive Point 00'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 311.005, 9.4512, 367.918 ),
                },
                ['ARMY_3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 38.5, 27.9922, 172.5 ),
                },
            },
        },
    },
    Chains = {
        ['Army1'] = {
            Markers = {
            },
        },
        ['Army2'] = {
            Markers = {
            },
        },
        ['LeftDown'] = {
            Markers = {
            },
        },
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '5',
    next_group_id = '1',
    next_unit_id = '2',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_3'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_4'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_8'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_5'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_7'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_6'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
