--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '1',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['AmphPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN03 AmphPN04' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 460.5, 32.9141, 204.5 ),
                },
                ['AirPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN04 AirPN02 AirPN05 AirPN03' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 256.5, 19.4609, 255.5 ),
                },
                ['Hydrocarbon 03'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 255.5, 14.9141, 128.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 216.5, 15, 426.5 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 191.5, 15.2422, 433.5 ),
                },
                ['Transport Marker 04'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 460.5, 37.5078, 255.5 ),
                },
                ['Mass 40'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 295.5, 15.0234, 85.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 200.5, 14.9141, 348.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 276.5, 28.2969, 447.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 471.5, 37.5078, 255.5 ),
                },
                ['AmphPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN08 AmphPN05 AmphPN03 AmphPN04' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 358.5, 22.7422, 204.5 ),
                },
                ['Combat Zone 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 255.5, 19.4609, 255.5 ),
                },
                ['Mass 33'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 103.5, 28.2969, 211.5 ),
                },
                ['Mass 39'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 328.5, 14.9766, 105.5 ),
                },
                ['Large Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ffff0080' ),
                    ['type'] = STRING( 'Large Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 255.5, 28.2969, 61.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 402.5, 28.2969, 310.5 ),
                },
                ['Mass 34'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 109.5, 28.2969, 201.5 ),
                },
                ['Mass 19'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 410.5, 28.2969, 308.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 319.5, 19.4766, 289.5 ),
                },
                ['Expansion Area 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 307.5, 19.4766, 306.5 ),
                },
                ['AmphPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN09 AmphPN05 AmphPN03 AmphPN02' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 22.8281, 307.5 ),
                },
                ['Mass 41'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 266.5, 28.2891, 45.5 ),
                },
                ['Mass 25'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 162.5, 22.4922, 382.5 ),
                },
                ['LandPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN06 LandPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 51.5, 32.9141, 307.5 ),
                },
                ['Mass 43'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 320.5, 15.2734, 78.5 ),
                },
                ['Mass 47'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 477.5, 21.4609, 27.5 ),
                },
                ['Transport Marker 05'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 204.5, 14.9141, 409.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 243.5, 27.3809, 420.5 ),
                },
                ['Transport Marker 03'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 51.5, 37.5078, 255.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 481.5, 32.9141, 192.5 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 481.5, 37.5078, 255.5 ),
                },
                ['AirPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN07 AirPN08 AirPN03' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 50.5, 28.2734, 50.5 ),
                },
                ['LandPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN07 LandPN01 LandPN09 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.5, 28.2969, 358.5 ),
                },
                ['AmphPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN03 AmphPN02' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.5, 22.4453, 409.5 ),
                },
                ['Transport Marker 06'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 307.5, 14.9141, 101.5 ),
                },
                ['AirPN08'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN09 AirPN06 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 50.5, 20.5859, 461.5 ),
                },
                ['Mass 36'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 151.5, 19.4844, 65.5 ),
                },
                ['Mass 26'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 30.5, 32.9141, 319.5 ),
                },
                ['AirPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN09 AirPN06 AirPN04' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 461.5, 22.375, 50.5 ),
                },
                ['Expansion Area 04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 204.5, 19.4766, 204.5 ),
                },
                ['AmphPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN09 AmphPN08 AmphPN07 AmphPN01' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 102.5, 28.2969, 153.5 ),
                },
                ['Mass 50'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 199.5, 19.4766, 235.5 ),
                },
                ['AmphPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN05 AmphPN04' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 102.5, 22.4531, 102.5 ),
                },
                ['Mass 30'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 147.5, 25.2891, 161.5 ),
                },
                ['Mass 35'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 111.5, 28.2969, 209.5 ),
                },
                ['AirPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN07 AirPN08 AirPN05' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 461.5, 28.2734, 461.5 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 347.5, 28.2891, 257.5 ),
                },
                ['AirPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN07 AirPN05 AirPN03' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 358.5, 22.4922, 153.5 ),
                },
                ['Mass 32'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 101.5, 28.2969, 203.5 ),
                },
                ['AmphPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN05 AmphPN02' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 51.5, 32.9141, 307.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 268.5, 27.3809, 91.5 ),
                },
                ['Mass 23'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 34.5, 21.4609, 484.5 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 183.5, 14.9844, 406.5 ),
                },
                ['AirPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN08 AirPN05 AirPN03' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 22.4922, 358.5 ),
                },
                ['Mass 42'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 235.5, 28.293, 64.5 ),
                },
                ['AmphPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN10 AmphPN09 AmphPN08 AmphPN06' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.5, 28.2969, 358.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 360.5, 19.4844, 446.5 ),
                },
                ['Mass 31'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 164.5, 28.2969, 254.5 ),
                },
                ['Mass 20'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 403.5, 32.9141, 225.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 364.5, 25.2891, 350.5 ),
                },
                ['LandPN07'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN03 LandPN08' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 460.5, 32.9141, 204.5 ),
                },
                ['Transport Marker 02'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 51.5, 28.2734, 50.5 ),
                },
                ['LandPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN05 LandPN01 LandPN09' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 22.3906, 460.5 ),
                },
                ['Mass 27'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 108.5, 32.9141, 286.5 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 256.5, 14.9141, 383.5 ),
                },
                ['Mass 21'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 24.5, 21.4609, 484.5 ),
                },
                ['LandPN06'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN05 LandPN02 LandPN09 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 102.5, 28.2969, 153.5 ),
                },
                ['Mass 28'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 41.5, 37.5078, 256.5 ),
                },
                ['Transport Marker 01'] = {
                    ['color'] = STRING( 'ff80A088' ),
                    ['type'] = STRING( 'Transport Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 460.5, 28.2734, 460.5 ),
                },
                ['AirPN05'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN06 AirPN04 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 358.5, 25.6953, 358.5 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 245.5, 28.2969, 466.5 ),
                },
                ['LandPN01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN04' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.5, 22.4453, 409.5 ),
                },
                ['Large Expansion Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ffff0080' ),
                    ['type'] = STRING( 'Large Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 256.5, 28.2969, 450.5 ),
                },
                ['LandPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN03 LandPN06' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 102.5, 22.4531, 102.5 ),
                },
                ['AmphPN04'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN10 AmphPN09 AmphPN07' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 358.5, 22.4375, 51.5 ),
                },
                ['LandPN09'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN08 LandPN06 LandPN04 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 22.8281, 307.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 311.5, 19.4766, 301.5 ),
                },
                ['AmphPN02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Amphibious Path Node' ),
                    ['adjacentTo'] = STRING( 'AmphPN08 AmphPN06 AmphPN01' ),
                    ['color'] = STRING( 'ff00ffff' ),
                    ['graph'] = STRING( 'DefaultAmphibious' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 22.3906, 460.5 ),
                },
                ['Expansion Area 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.5, 28.2969, 306.5 ),
                },
                ['Combat Zone 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 409.5, 32.6328, 255.5 ),
                },
                ['Mass 24'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 34.5, 21.4609, 495.5 ),
                },
                ['Mass 48'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 200.5, 19.4844, 210.5 ),
                },
                ['Expansion Area 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008080' ),
                    ['type'] = STRING( 'Expansion Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 102.5, 28.2969, 205.5 ),
                },
                ['Mass 49'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 192.5, 19.4766, 222.5 ),
                },
                ['Protected Experimental Construction 02'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 255.5, 28.2969, 50.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 408.5, 28.2969, 300.5 ),
                },
                ['Mass 46'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 487.5, 21.4609, 27.5 ),
                },
                ['Protected Experimental Construction 01'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 256.5, 28.2969, 461.5 ),
                },
                ['LandPN10'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN03 LandPN08 LandPN06 LandPN09' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 358.5, 22.7422, 204.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 312.5, 19.4766, 276.5 ),
                },
                ['Mass 45'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 477.5, 21.4609, 16.5 ),
                },
                ['Hydrocarbon 02'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Hydrocarbon_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 311.5, 14.9141, 163.5 ),
                },
                ['Mass 29'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 31.5, 37.5078, 256.5 ),
                },
                ['AirPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Air Path Node' ),
                    ['adjacentTo'] = STRING( 'AirPN01 AirPN09 AirPN04 AirPN02' ),
                    ['color'] = STRING( 'ffffffff' ),
                    ['graph'] = STRING( 'DefaultAir' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 153.5, 25.6953, 153.5 ),
                },
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 400.5, 28.2969, 302.5 ),
                },
                ['LandPN03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Land Path Node' ),
                    ['adjacentTo'] = STRING( 'LandPN07 LandPN02 LandPN10' ),
                    ['color'] = STRING( 'ff00ff00' ),
                    ['graph'] = STRING( 'DefaultLand' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Path_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 358.5, 22.4375, 51.5 ),
                },
                ['Combat Zone 03'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 102.5, 32.5, 256.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '8',
    next_group_id = '6',
    next_unit_id = '128',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_9'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                    ['WRECKAGE'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_149'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 150.500000, 25.306641, 167.500000 },
                                Orientation = { 0.000000, -1.099557, 0.000000 },
                            },
                            ['UNIT_79'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 253.759140, 19.455868, 261.407990 },
                                Orientation = { 0.000000, -5.681056, 0.000000 },
                            },
                            ['UNIT_141'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 148.500000, 25.322266, 169.500000 },
                                Orientation = { 0.000000, -0.724310, 0.000000 },
                            },
                            ['UNIT_94'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 150.500000, 20.460938, 474.500000 },
                                Orientation = { 0.000000, 0.733038, 0.000000 },
                            },
                            ['UNIT_88'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 150.500000, 20.460938, 483.500000 },
                                Orientation = { 0.000000, -2.888519, 0.000000 },
                            },
                            ['UNIT_114'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 25.306641, 344.500000 },
                                Orientation = { 0.000000, 2.042036, 0.000000 },
                            },
                            ['UNIT_148'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 149.500000, 25.289063, 160.500000 },
                                Orientation = { 0.000000, 0.523596, 0.000000 },
                            },
                            ['UNIT_91'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 156.500000, 20.460938, 479.500000 },
                                Orientation = { 0.000000, -1.858775, 0.000000 },
                            },
                            ['UNIT_127'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 242.240906, 19.468750, 255.591949 },
                                Orientation = { 0.000000, -14.398975, 0.000000 },
                            },
                            ['UNIT_58'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 255.759155, 19.462818, 267.407990 },
                                Orientation = { 0.000000, -2.740166, 0.000000 },
                            },
                            ['UNIT_109'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 25.289063, 347.500000 },
                                Orientation = { 0.000000, 2.042036, 0.000000 },
                            },
                            ['UNIT_150'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 240.240906, 19.471169, 250.592010 },
                                Orientation = { 0.000000, -7.051130, 0.000000 },
                            },
                            ['UNIT_83'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 261.759094, 19.460938, 261.407990 },
                                Orientation = { 0.000000, -11.257383, 0.000000 },
                            },
                            ['UNIT_130'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 256.240845, 19.459309, 244.592010 },
                                Orientation = { 0.000000, -5.881759, 0.000000 },
                            },
                            ['UNIT_124'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 357.500000, 20.460938, 30.500000 },
                                Orientation = { 0.000000, -5.550146, 0.000000 },
                            },
                            ['UNIT_93'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 147.500000, 20.460938, 479.500000 },
                                Orientation = { 0.000000, 0.994838, 0.000000 },
                            },
                            ['UNIT_143'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 246.240906, 19.460938, 249.592010 },
                                Orientation = { 0.000000, -6.675885, 0.000000 },
                            },
                            ['UNIT_60'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 242.759140, 19.469517, 258.407990 },
                                Orientation = { 0.000000, -2.687806, 0.000000 },
                            },
                            ['UNIT_116'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 363.500000, 25.322266, 342.500000 },
                                Orientation = { 0.000000, 2.417283, 0.000000 },
                            },
                            ['UNIT_139'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 20.460938, 40.500000 },
                                Orientation = { 0.000000, -2.879794, 0.000000 },
                            },
                            ['UNIT_134'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 262.240875, 19.449936, 256.591919 },
                                Orientation = { 0.000000, -10.210176, 0.000000 },
                            },
                            ['UNIT_145'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 355.500000, 20.460938, 28.500000 },
                                Orientation = { 0.000000, -5.000368, 0.000000 },
                            },
                            ['UNIT_128'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 355.500000, 20.460938, 32.500000 },
                                Orientation = { 0.000000, -5.000368, 0.000000 },
                            },
                            ['UNIT_97'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 147.500000, 20.460938, 472.500000 },
                                Orientation = { 0.000000, 0.584685, 0.000000 },
                            },
                            ['UNIT_92'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 156.500000, 20.460938, 483.500000 },
                                Orientation = { 0.000000, -1.858775, 0.000000 },
                            },
                            ['UNIT_135'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 364.500000, 20.460938, 32.500000 },
                                Orientation = { 0.000000, -2.146755, 0.000000 },
                            },
                            ['UNIT_89'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 153.500000, 20.460938, 484.500000 },
                                Orientation = { 0.000000, -2.888519, 0.000000 },
                            },
                            ['UNIT_137'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 269.240875, 19.476563, 253.592010 },
                                Orientation = { 0.000000, -5.829399, 0.000000 },
                            },
                            ['UNIT_138'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 152.500000, 25.298828, 162.500000 },
                                Orientation = { 0.000000, -1.151921, 0.000000 },
                            },
                            ['UNIT_126'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 153.500000, 25.376953, 158.500000 },
                                Orientation = { 0.000000, -0.549783, 0.000000 },
                            },
                            ['UNIT_78'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 264.759094, 19.444199, 256.408051 },
                                Orientation = { 0.000000, -5.681056, 0.000000 },
                            },
                            ['UNIT_113'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 359.500000, 25.710938, 359.500000 },
                                Orientation = { 0.000000, 2.652898, 0.000000 },
                            },
                            ['UNIT_80'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 245.759140, 19.462820, 256.408051 },
                                Orientation = { 0.000000, -7.461290, 0.000000 },
                            },
                            ['UNIT_62'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 242.759140, 19.476563, 261.407990 },
                                Orientation = { 0.000000, -3.604105, 0.000000 },
                            },
                            ['UNIT_146'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 247.240906, 19.460938, 255.591949 },
                                Orientation = { 0.000000, -8.822649, 0.000000 },
                            },
                            ['UNIT_112'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 358.500000, 25.376953, 353.500000 },
                                Orientation = { 0.000000, 2.591810, 0.000000 },
                            },
                            ['UNIT_142'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 363.500000, 20.460938, 35.500000 },
                                Orientation = { 0.000000, -2.242748, 0.000000 },
                            },
                            ['UNIT_125'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 150.500000, 25.289063, 164.500000 },
                                Orientation = { 0.000000, -1.099557, 0.000000 },
                            },
                            ['UNIT_131'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 254.240906, 19.452356, 248.592010 },
                                Orientation = { 0.000000, -7.051130, 0.000000 },
                            },
                            ['UNIT_136'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 149.500000, 25.310547, 168.500000 },
                                Orientation = { 0.000000, -1.326448, 0.000000 },
                            },
                            ['UNIT_69'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 259.759094, 19.460938, 265.407990 },
                                Orientation = { 0.000000, -3.604105, 0.000000 },
                            },
                            ['UNIT_133'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 250.240906, 19.460938, 254.592010 },
                                Orientation = { 0.000000, -8.107055, 0.000000 },
                            },
                            ['UNIT_120'] = {
                                type = 'uea0104',
                                orders = '',
                                platoon = '',
                                Position = { 149.500000, 25.367188, 170.000000 },
                                Orientation = { 0.000000, -3.970625, 0.000000 },
                            },
                            ['UNIT_144'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 364.500000, 20.460938, 39.500000 },
                                Orientation = { 0.000000, -2.556908, 0.000000 },
                            },
                            ['UNIT_87'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 249.759140, 19.460938, 255.408096 },
                                Orientation = { 0.000000, -7.068584, 0.000000 },
                            },
                            ['UNIT_132'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 252.240906, 19.460938, 246.592010 },
                                Orientation = { 0.000000, -6.745697, 0.000000 },
                            },
                            ['UNIT_115'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 362.500000, 25.310547, 343.500000 },
                                Orientation = { 0.000000, 1.815145, 0.000000 },
                            },
                            ['UNIT_108'] = {
                                type = 'uea0104',
                                orders = '',
                                platoon = '',
                                Position = { 362.500000, 25.367188, 342.000000 },
                                Orientation = { 0.000000, -0.829032, 0.000000 },
                            },
                            ['UNIT_118'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 258.240875, 19.442125, 250.592010 },
                                Orientation = { 0.000000, -8.822649, 0.000000 },
                            },
                            ['UNIT_151'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 250.240906, 19.460938, 250.592010 },
                                Orientation = { 0.000000, -14.398975, 0.000000 },
                            },
                            ['UNIT_50'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 265.759094, 19.460938, 262.407990 },
                                Orientation = { 0.000000, -3.534292, 0.000000 },
                            },
                            ['UNIT_111'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 362.500000, 25.289063, 351.500000 },
                                Orientation = { 0.000000, 3.665189, 0.000000 },
                            },
                            ['UNIT_64'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 257.759094, 19.460169, 263.407990 },
                                Orientation = { 0.000000, -3.909537, 0.000000 },
                            },
                            ['UNIT_122'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 20.460938, 28.500000 },
                                Orientation = { 0.000000, -6.030112, 0.000000 },
                            },
                            ['UNIT_51'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 271.759094, 19.468750, 261.407990 },
                                Orientation = { 0.000000, -3.909537, 0.000000 },
                            },
                            ['UNIT_119'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 152.500000, 25.710938, 152.500000 },
                                Orientation = { 0.000000, -0.488695, 0.000000 },
                            },
                            ['UNIT_117'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 364.500000, 25.351563, 341.500000 },
                                Orientation = { 0.000000, 1.972224, 0.000000 },
                            },
                            ['UNIT_129'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 147.500000, 25.351563, 170.500000 },
                                Orientation = { 0.000000, -1.169369, 0.000000 },
                            },
                            ['UNIT_86'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 261.759094, 19.456312, 257.407990 },
                                Orientation = { 0.000000, -4.965462, 0.000000 },
                            },
                            ['UNIT_121'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 361.500000, 20.460938, 37.500000 },
                                Orientation = { 0.000000, -2.408555, 0.000000 },
                            },
                            ['UNIT_110'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 359.500000, 25.298828, 349.500000 },
                                Orientation = { 0.000000, 1.989672, 0.000000 },
                            },
                            ['UNIT_140'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 358.500000, 20.460938, 27.500000 },
                                Orientation = { 0.000000, -6.030112, 0.000000 },
                            },
                            ['UNIT_123'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 269.240875, 19.476563, 250.592010 },
                                Orientation = { 0.000000, -6.745697, 0.000000 },
                            },
                            ['UNIT_96'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 150.500000, 20.460938, 471.500000 },
                                Orientation = { 0.000000, 0.261799, 0.000000 },
                            },
                            ['UNIT_90'] = {
                                type = 'url0107',
                                orders = '',
                                platoon = '',
                                Position = { 154.500000, 20.460938, 481.500000 },
                                Orientation = { 0.000000, -2.408553, 0.000000 },
                            },
                            ['UNIT_85'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 269.759094, 19.475794, 256.408051 },
                                Orientation = { 0.000000, -11.257383, 0.000000 },
                            },
                            ['UNIT_147'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 266.240875, 19.462820, 255.591949 },
                                Orientation = { 0.000000, -10.602882, 0.000000 },
                            },
                            ['UNIT_95'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 148.500000, 20.460938, 476.500000 },
                                Orientation = { 0.000000, 0.898845, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
