--[[  Scenario                                                           		]]--
--[[  																					]]--
--[[	Generated by FAF Map Editor								]]--
--[[	Contact: ozonexo3@gmail.com								]]--
--[[																					]]--
Scenario = {
    next_area_id = '4',
    --[[																				]]--
    --[[  Props                                                                    ]]--
    --[[																				]]--
    Props = {
    },
    --[[																				]]--
    --[[  Areas                                                                    ]]--
    --[[																				]]--
    Areas = {
        ['AREA_1'] = {
[*AREA*]
        },
    },
    --[[																				]]--
    --[[  Markers																]]--
    --[[																				]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 61.7549, 24.6, 233.819 ),
                },
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 447.535, 19.9375, 281.811 ),
                },
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['SpawnWithArmy'] = STRING( 'ARMY_1' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 38.5, 27.9922, 354.5 ),
                },
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 256.566, 37.7523, 74.7763 ),
                },
[*MARKERS*]
            },
        },
    },
    Chains = {
[*CHAINS*]
    },
    --[[																				]]--
    --[[  Orders																	]]--
    --[[																				]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[																				]]--
    --[[  Platoons																]]--
    --[[																				]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[																				]]--
    --[[  Armies																	]]--
    --[[																				]]--
    next_army_id = '5',
    next_group_id = '1',
    next_unit_id = '2',
    Armies = 
    {
[*ARMYS*]
    },
}